name: GitHub Actions Demo - shimada-kai
on:
  pull_request:
    branches:
      - main

jobs:
  echo-my-message:
    # runs-onは変更しないでください!!!（ランナーの種類によって料金が変わり、macOSとかは高くなるので!）
    runs-on: ubuntu-latest
    steps:
      - name: Hello World!
        run: |
          exit 1
